from __future__ import annotations

from app.identity_auth.commands import (
    AccountLockedError,
    InvalidCredentialsError,
    LoginResult,
    PasswordResetTokenInvalidError,
    ReauthResult,
    TotpEnrolResult,
    TotpInvalidError,
    TotpRequiredError,
    confirm_password_reset,
    enrol_totp,
    entra_callback,
    local_login,
    logout,
    reauth,
    request_password_reset,
    verify_totp,
)
from app.identity_auth.dependencies import (
    CsrfTokenInvalidError,
    ReauthRequiredError,
    SessionExpiredError,
    get_current_session,
    require_csrf,
    require_reauth,
)
from app.identity_auth.security import (
    PasswordHasher,
    PasswordPolicyError,
    generate_csrf_token,
    generate_totp_secret,
    is_breached_password,
    totp_provisioning_uri,
    validate_password_policy,
    verify_totp_code,
)

__all__ = [
    "PasswordHasher",
    "PasswordPolicyError",
    "validate_password_policy",
    "is_breached_password",
    "generate_totp_secret",
    "totp_provisioning_uri",
    "verify_totp_code",
    "generate_csrf_token",
    "InvalidCredentialsError",
    "AccountLockedError",
    "TotpRequiredError",
    "TotpInvalidError",
    "PasswordResetTokenInvalidError",
    "LoginResult",
    "local_login",
    "entra_callback",
    "logout",
    "ReauthResult",
    "reauth",
    "request_password_reset",
    "confirm_password_reset",
    "TotpEnrolResult",
    "enrol_totp",
    "verify_totp",
    "SessionExpiredError",
    "CsrfTokenInvalidError",
    "ReauthRequiredError",
    "get_current_session",
    "require_csrf",
    "require_reauth",
]
