#!/usr/bin/env bash
# Repository hygiene gate (D-262). Runs in CI and locally before a push.
#  1. Tracked paths must stay inside the allowlist (no local tooling, plans or prompts in version control).
#  2. Commit messages in the PR range carry no attribution trailers or "generated with" lines.
#  3. Required project files exist; Makefile targets referenced by CI exist; no forbidden technology in source.
#   scripts/repo-doctor.sh [--base <ref>]     (default base: origin/main if it exists, else the root commit)
set -uo pipefail
cd "$(dirname "$0")/.."
rc=0
ok()  { printf '✔ %s\n' "$*"; }
bad() { printf '✘ %s\n' "$*"; rc=1; }

base="${2:-}"
[ "${1:-}" = "--base" ] && base="$2"
if [ -z "$base" ]; then
  if git rev-parse --verify -q origin/main >/dev/null; then base="origin/main"; else base="$(git rev-list --max-parents=0 HEAD | tail -n1)"; fi
fi

# --- 1. tracked-path allowlist -------------------------------------------------------------------
ROOT_ALLOW="README.md Makefile docker-compose.yml .env.example .gitignore package.json pnpm-workspace.yaml pnpm-lock.yaml apps packages infra docs scripts tests .github LICENSE .gitleaks.toml .prettierignore .prettierrc.json"
DOCS_ALLOW="spec adr reviews"
SCRIPTS_ALLOW="verify.sh security.sh pr-body.sh repo-doctor.sh seed"
viol=0
while IFS= read -r f; do
  top="${f%%/*}"
  case " $ROOT_ALLOW " in *" $top "*) ;; *) bad "tracked path outside allowlist: $f"; viol=1; continue ;; esac
  if [ "$top" = "docs" ]; then
    sub="$(printf '%s' "$f" | cut -d/ -f2)"
    case " $DOCS_ALLOW " in *" $sub "*) ;; *) bad "docs/ path outside allowlist: $f"; viol=1 ;; esac
    case "$f" in docs/spec/reference/*) bad "reference material must not be tracked: $f"; viol=1 ;; esac
  fi
  if [ "$top" = "scripts" ]; then
    sub="$(printf '%s' "$f" | cut -d/ -f2)"
    case " $SCRIPTS_ALLOW " in *" $sub "*) ;; *) bad "scripts/ path outside allowlist: $f"; viol=1 ;; esac
  fi
done < <(git ls-files)
[ $viol = 0 ] && ok "tracked paths within allowlist ($(git ls-files | wc -l | tr -d ' ') files)"

# --- 2. commit message hygiene --------------------------------------------------------------------
if git rev-parse --verify -q "$base" >/dev/null; then
  range="$base..HEAD"
  if git log --format=%B "$range" 2>/dev/null | grep -Eiq '^(co-authored-by|[a-z-]+-session):|generated with|generated by'; then
    bad "attribution trailer or 'generated with' line found in commit messages ($range)"
    git log --format='--- %h %s%n%b' "$range" | grep -Ein '^(co-authored-by|[a-z-]+-session):|generated with|generated by' | head -n 10
  else
    ok "commit messages clean ($range)"
  fi
fi

# --- 3. required files, make targets, forbidden technology ----------------------------------------
for f in README.md Makefile docker-compose.yml .env.example .github/workflows/ci.yml docs/spec/FREEZE_ADDENDUM.md docs/spec/FROZEN_DECISIONS.md docs/spec/VERIFY.md docs/spec/schema_v1.sql docs/spec/schema_v2_reconciliation.sql scripts/verify.sh scripts/security.sh; do
  [ -f "$f" ] && ok "present $f" || bad "missing $f"
done
for t in dev verify lint typecheck test db-check contracts security seed e2e release-verify; do
  grep -qE "^${t}:" Makefile && ok "make $t" || bad "Makefile missing target $t"
done
if git ls-files apps packages 2>/dev/null | xargs -r grep -Eil 'EntityFramework|DbContext|Microsoft\.EntityFrameworkCore|oracledb|cx_Oracle|minio|pinecone|chromadb|weasyprint|kubernetes|turbo\.json' 2>/dev/null | grep -q .; then
  bad "forbidden technology reference in tracked apps/ or packages/"
else
  ok "no forbidden technology references"
fi

[ $rc = 0 ] && echo "repo-doctor: PASS" || echo "repo-doctor: FAIL"
exit $rc
